name: Upload HAProxy Config & Script (Reusable)

on:
  workflow_call:
    inputs:
      environment:
      storageAccount:
        required: true
        type: string

      container:
        required: true
        type: string

      haproxyConfigPath:
        required: true
        type: string

      haproxyConfigBlobName:
        required: true
        type: string

      installScriptPath:
        required: true
        type: string

      installScriptBlobName:
        required: true
        type: string

    secrets:
      azureCredentials:
        required: true

jobs:
  upload-haproxy-files:
    name: Upload HAProxy Config & Script
    runs-on:
      group: azure-large-runners
      labels: ubuntu-azure-large

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.azureCredentials }}

      - name: Validate files
        run: |
          set -e
          test -f "${{ inputs.haproxyConfigPath }}"
          test -f "${{ inputs.installScriptPath }}"

      - name: Ensure container exists
        run: |
          az storage container create \
            --account-name "${{ inputs.storageAccount }}" \
            --name "${{ inputs.container }}" \
            --auth-mode login

      - name: Upload HAProxy config
        run: |
          az storage blob upload \
            --account-name "${{ inputs.storageAccount }}" \
            --container-name "${{ inputs.container }}" \
            --file "${{ inputs.haproxyConfigPath }}" \
            --name "${{ inputs.haproxyConfigBlobName }}" \
            --overwrite true \
            --auth-mode login

      - name: Upload Install Script
        run: |
          az storage blob upload \
            --account-name "${{ inputs.storageAccount }}" \
            --container-name "${{ inputs.container }}" \
            --file "${{ inputs.installScriptPath }}" \
            --name "${{ inputs.installScriptBlobName }}" \
            --overwrite true \
            --auth-mode login
