name: Upload HAProxy Config & Script

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      storageAccount:
        required: true
        type: string
      container:
        required: true
        type: string
      haproxyConfigPath:
        required: true
        type: string
      haproxyConfigBlobName:
        required: true
        type: string
      installScriptPath:
        required: true
        type: string
      installScriptBlobName:
        required: true
        type: string

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload files
        uses: azure/cli@v2
        with:
          inlineScript: |
            az storage blob upload \
              --auth-mode login \
              --account-name "${{ inputs.storageAccount }}" \
              --container-name "${{ inputs.container }}" \
              --file "${{ inputs.haproxyConfigPath }}" \
              --name "${{ inputs.haproxyConfigBlobName }}" \
              --overwrite true

            az storage blob upload \
              --auth-mode login \
              --account-name "${{ inputs.storageAccount }}" \
              --container-name "${{ inputs.container }}" \
              --file "${{ inputs.installScriptPath }}" \
              --name "${{ inputs.installScriptBlobName }}" \
              --overwrite true
